"ext: app":
  - app/*

"ext: lib":
  - lib/*

"ext: public":
  - public/*

"ext: styles":
  - styles/*

"module: pages":
  - pages/*

"module: components":
  - components/*

"topic: build":
  - package.json
  - yarn.lock
  - "*.config.js"
  - tsconfig.json

"topic: ci":
  - .github/*

"topic: docker":
  - docker-compose.yml
  - docker-compose.test.yml
  - Dockerfile
  - traefik.yml
  - .dockerignore

"topic: docs":
  - README.md
  - CONTRIBUTING.md
  - CODE_OF_CONDUCT.md

"topic: style":
  - .eslintrc.json
  - .prettierignore
