name: builds

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  docker:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Build & run docker
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
          NEXT_PUBLIC_REDIRECT_URI: ${{ secrets.NEXT_PUBLIC_REDIRECT_URI }}
        run: docker-compose up -d --build
      - name: Docker sanity check
        run: sleep 20 && nc -vz localhost 3000
      - name: Debug
        run: docker-compose logs
      - name: Ping server
        run: curl http://localhost:3000
