name: push
on:
  push:
    branches: main

jobs:
  dockerhub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
          NEXT_PUBLIC_REDIRECT_URI: ${{ secrets.NEXT_PUBLIC_REDIRECT_URI }}
          NEXT_PUBLIC_CHATWOOT_ENDPOINT: ${{ secrets.NEXT_PUBLIC_CHATWOOT_ENDPOINT }}
          NEXT_PUBLIC_CHATWOOT_TOKEN: ${{ secrets.NEXT_PUBLIC_CHATWOOT_TOKEN }}
        run: docker build . -t quackai/platform:latest
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: quackai
          password: ${{ secrets.DOCKERHUB_PW }}
      - name: Push to hub
        run: docker push quackai/platform:latest

  deploy-dev:
    needs: dockerhub
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_DEV_HOST }}
          username: ${{ secrets.SSH_DEV_USERNAME }}
          key: ${{ secrets.SSH_DEPLOY_DEV }}
          script: |
            docker pull quackai/platform:latest
            docker rmi -f $(docker images -f "dangling=true" -q)
            cd devops && docker compose stop frontend && docker compose up -d
            docker inspect -f '{{ .Created }}' $(docker compose images -q frontend)
      - name: Ping server
        env:
          APP_URL: ${{ secrets.NEXT_PUBLIC_REDIRECT_URI }}
        run: sleep 10 && curl $APP_URL
