name: push
on:
  push:
    branches: main

jobs:
  dockerhub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
          NEXT_PUBLIC_REDIRECT_URI: ${{ secrets.NEXT_PUBLIC_REDIRECT_URI }}
          NEXT_PUBLIC_CHATWOOT_ENDPOINT: ${{ secrets.NEXT_PUBLIC_CHATWOOT_ENDPOINT }}
          NEXT_PUBLIC_CHATWOOT_TOKEN: ${{ secrets.NEXT_PUBLIC_CHATWOOT_TOKEN }}
        run: docker build . -t quackai/platform:latest
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: quackai
          password: ${{ secrets.DOCKERHUB_PW }}
      - name: Push to hub
        run: docker push quackai/platform:latest

  check-docker:
    needs: dockerhub
    runs-on: ubuntu-latest
    steps:
      - name: Run the latest image
        run: |
          docker pull quackai/platform:latest
          docker inspect -f '{{ .Created }}' quackai/platform:latest
